version: '3.8'

services:

  database:
    build: 
      context: .
      dockerfile: ./.docker/db/db.dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'ggg'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    container_name: database
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - ggg-network
    volumes:
      - ggg-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 5003:80
    environment:
      - 'PMA_HOST=database'
      - 'PMA_PORT=3306'
    networks:
      - ggg-network
    container_name: phpmyadmin

volumes:
  ggg-db:

networks:
  ggg-network: